name: Updates java

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run dependency update script
        run: make deps-java-update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update java
          branch: update-java
          title: 'Update java'
          body: |
            This pull request updates the JDK:
            - Current plugin updates
          labels: JDK
